apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URL: mongodb://m4k_user:m4k_password@mongo-0.mongo.m4k-pipeline.svc.cluster.local:27017/m4kdb?authSource=admin
  MONGO_INITDB_ROOT_USERNAME: m4k_user
  MONGO_INITDB_ROOT_PASSWORD: m4k_password
