apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: m4k-pipeline

resources:
  - namespace.yaml
  - app-secret.yaml
  - mongo-service.yaml
  - mongo-statefulset.yaml
  - deployment.yaml
  - service.yaml
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - hpa.yaml
